### ISSUE TITLE
Error on Win11

### ISSUE THREAD

**Issue by subsoap** [zachdaniel/twitter#3]
```
warning: Exception.exception?/1 is deprecated. Use Kernel.is_exception/1 instead
  lib/twitter/accounts/accounts.ex:1

[error] Task #PID<0.540.0> started from TwitterWeb.Endpoint terminating
** (UndefinedFunctionError) function :http_util.timestamp/0 is undefined (module :http_util is not available)
    (inets 9.0.2) :http_util.timestamp()
    (inets 9.0.2) httpc.erl:750: :httpc.handle_request/9
    (esbuild 0.6.0) lib/esbuild.ex:336: Esbuild.fetch_body!/1
    (esbuild 0.6.0) lib/esbuild.ex:217: Esbuild.install/0
    (esbuild 0.6.0) lib/esbuild.ex:189: Esbuild.install_and_run/2
    (phoenix 1.7.0-rc.2) lib/phoenix/endpoint/watcher.ex:19: Phoenix.Endpoint.Watcher.watch/2
    (elixir 1.15.4) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
Function: &Phoenix.Endpoint.Watcher.watch/2
    Args: ["esbuild", {Esbuild, :install_and_run, [:default, ["--sourcemap=inline", "--watch"]]}]
[error] Task #PID<0.541.0> started from TwitterWeb.Endpoint terminating
** (UndefinedFunctionError) function :http_util.timestamp/0 is undefined (module :http_util is not available)
    (inets 9.0.2) :http_util.timestamp()
    (inets 9.0.2) httpc.erl:750: :httpc.handle_request/9
    (tailwind 0.1.9) lib/tailwind.ex:324: Tailwind.fetch_body!/1
    (tailwind 0.1.9) lib/tailwind.ex:230: Tailwind.install/0
    (tailwind 0.1.9) lib/tailwind.ex:215: Tailwind.install_and_run/2
    (phoenix 1.7.0-rc.2) lib/phoenix/endpoint/watcher.ex:19: Phoenix.Endpoint.Watcher.watch/2
    (elixir 1.15.4) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
Function: &Phoenix.Endpoint.Watcher.watch/2
    Args: ["tailwind", {Tailwind, :install_and_run, [:default, ["--watch"]]}]
[debug] Downloading tailwind from https://github.com/tailwindlabs/tailwindcss/releases/download/v3.1.8/tailwindcss-windows-x64.exe
[debug] Downloading esbuild from https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-0.14.41.tgz
[error] Task #PID<0.552.0> started from TwitterWeb.Endpoint terminating
** (UndefinedFunctionError) function :http_util.timestamp/0 is undefined (module :http_util is not available)
    (inets 9.0.2) :http_util.timestamp()
    (inets 9.0.2) httpc.erl:750: :httpc.handle_request/9
    (tailwind 0.1.9) lib/tailwind.ex:324: Tailwind.fetch_body!/1
    (tailwind 0.1.9) lib/tailwind.ex:230: Tailwind.install/0
    (tailwind 0.1.9) lib/tailwind.ex:215: Tailwind.install_and_run/2
    (phoenix 1.7.0-rc.2) lib/phoenix/endpoint/watcher.ex:19: Phoenix.Endpoint.Watcher.watch/2
    (elixir 1.15.4) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
Function: &Phoenix.Endpoint.Watcher.watch/2
    Args: ["tailwind", {Tailwind, :install_and_run, [:default, ["--watch"]]}]
[error] Task #PID<0.551.0> started from TwitterWeb.Endpoint terminating
** (UndefinedFunctionError) function :http_util.timestamp/0 is undefined (module :http_util is not available)
    (inets 9.0.2) :http_util.timestamp()
    (inets 9.0.2) httpc.erl:750: :httpc.handle_request/9
    (esbuild 0.6.0) lib/esbuild.ex:336: Esbuild.fetch_body!/1
    (esbuild 0.6.0) lib/esbuild.ex:217: Esbuild.install/0
    (esbuild 0.6.0) lib/esbuild.ex:189: Esbuild.install_and_run/2
    (phoenix 1.7.0-rc.2) lib/phoenix/endpoint/watcher.ex:19: Phoenix.Endpoint.Watcher.watch/2
    (elixir 1.15.4) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
Function: &Phoenix.Endpoint.Watcher.watch/2
    Args: ["esbuild", {Esbuild, :install_and_run, [:default, ["--sourcemap=inline", "--watch"]]}]
[info] Running TwitterWeb.Endpoint with cowboy 2.9.0 at 127.0.0.1:4000 (http)
[info] Access TwitterWeb.Endpoint at http://localhost:4000
[debug] Downloading tailwind from https://github.com/tailwindlabs/tailwindcss/releases/download/v3.1.8/tailwindcss-windows-x64.exe
[debug] Downloading esbuild from https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-0.14.41.tgz
warning: Exception.exception?/1 is deprecated. Use Kernel.is_exception/1 instead
  lib/twitter/accounts/resources/friend_link.ex:8
```

**Comment by zachdaniel** [comment]
AFAIK this isn't an issue specific to this project, but something that looks related to esbuild or some related dependency. Going to close this with that in mind.
